### PR TITLE
-added status bar background

### LINKED ISSUE #33: Status Bar Should not hover over contacts screen view on iOS
image

### PR DESCRIPTION
**Pull request by radusepe**
-fixed profile picture displaying issue
-fixed radius on names
-fixes #33

### CODE REVIEW

**Comment by radusepe** [comment]
Looks like this now:

image

**Comment by a1gemmel** [comment]
This is fine
image
Your status bar renders belong the android bar.
I think the android api for border radius is kind of fucky, it doesn't behave the same way as iOS.

We may need to go with some global environment switches to fix these kinds of things.

**Comment by radusepe** [comment]
image

So I finally got the android emulator working and now I'm confused. Notice the perfect circular profile pictures. I will work on the status bar, but could someone run this branch on an actual android device instead of an emulator and take a screenshot of the contacts view? I'm wondering which profile pictures it uses on an actual device.

**Comment by a1gemmel** [comment]
Didn't bring a usb cable home with me :/ If Adam doesn't get to it I'll be able to check it out on Sunday
That's the weirdest thing...

**Comment by arafeek** [comment]
Tested on android 7.1.1 on nexus 5x and looks okay to me
16936057_10154131350126205_2059667766_o

**Comment by radusepe** [comment]
The circles seem a bit off, but I'm going to merge this for now.

**Pull request merged**
