### PR TITLE
Added custom field support

### LINKED ISSUE #73: UI/UX for custom field creation
What does this work flow look like?
Mockups or a decision tree would be nice.

### PR DESCRIPTION
**Pull request by radusepe**
fixes #73 
additionally:
-added StatusBar back to profile page only for android (it loaded as black otherwise)
-added underlineColorAndroid='transparent' to TextInput which seems to remove the ugly lines you see on android for editable fields

### CODE REVIEW

**Comment by a1gemmel** [comment]
I noticed you used a modal in this, it might be a pain to merge branches but in  #90 I created a common CordialModal asset that abstracts a lot of that away, like the styling and the close button. 

If #90 gets merged first then this could be rewritten to take advantage of that.

**Comment by radusepe** [comment]
Once #90 gets merged I will fix what I have to with this issue regarding the Modal and then this PR can be reviewed.

**Comment by arafeek** [comment]
@radusepe does this require refactoring to use the new modal?

**Comment by radusepe** [comment]
@arafeek Yeah, I'll have it refactored by tonight

**Pull request closed without merging**
