### PR TITLE
added support for multiple cards

### PR DESCRIPTION
**Pull request by radusepe**
The Look and behaviour is basically what was talked about in #71 
I am having some trouble deleting cards (not very familiar with what is going on with that code)
Also everything works smoothly on iOS, but on android things are breaking and I'm not sure why. Been working on this all day so not sure how much longer I can go on it. Will keep trying to resolve the issue but maybe someone else can help spot the problem.

### CODE REVIEW

**Comment by a1gemmel** [comment]
I'll take a look and see if I can fix things

**Comment by a1gemmel** [comment]
Ok, I've figured out the problem and I will fix it.

TL;DR: zIndex reorders components, reordering is not sent to java properly, on rerender the conditionally-rendering components signal for the wrong components to be removed. 'Elevation' prop is a workaround for android, similar to zIndex but does not change *touchable* order. So the order has to be manually set via juggling the jsx.

**Comment by a1gemmel** [comment]
@radusepe 
Ok, I made the zIndexing work on Android and made deletes actually delete. There is still a bit of work to be done to make routing work.
You have a weird routing thing here where once the card is deleted, the route you return to has no card and dies traumatically. I would suggest not using state to store the current card's id for the card container, but rather using routing to achieve that. Like, instead of changing state on card selection, change the route and pass in the id as a prop.

**Comment by radusepe** [comment]
Ok so from the rigorous testing I've done, this feature seems to work.
A couple things have come up and if they can be fixed that would be amazing (I can't seem to figure it out), but in terms of the demo I think we can show off this feature.

List of issues:
- Android hates me beyond belief and I can't get the inner component to not overflow
image
- There are no animations happening between when you delete a card and the view updates to a different card, or when you create a new card and the list of cards adds that new entry. I'm not sure how to go about doing this.
- Not sure how to close the tray without explicitly hitting the 'Cancel' button. It would be nice if it closed when you clicked away from it.

But as I said this seems to work now. If you want to pull the branch and check it out cool. If you feel like the feature is not complete enough to submit or demo, I understand.

**Pull request merged**
