### PR TITLE
UI and QOL tweaks for contacts view.

### PR DESCRIPTION
**Pull request by arafeek**
image

* it says tweaks, but I understand this is a pretty drastic UI redo, thoughts? Each button will correctly open with autoLinker

### CODE REVIEW

**Comment by shivangipatwardhan2018** [comment]
That looks really nice! does it always only display the top 2 contact links?

**Comment by arafeek** [comment]
Yeah so it will return as many as the first 3 links in their card.

**Comment by a1gemmel** [comment]
I like it, looks clean. 
If I can be nitpicky, bigger lineweight on the separation between each card and also the search bar would be good. As well as cutting the name size down, even "Dennis Reynolds" is being pushed to 2 lines and that's not a particularly long name.

**Comment by arafeek** [comment]
Valid comments, will make those changes

**Pull request merged**
